# fly.toml app configuration file generated for spi on 2023-06-13T15:28:21+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = "spi"
primary_region = "lhr"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[env]
NODE_ENV = "production"
